---
- name: Unzip Grid binaries
  unarchive: src="{{ grid_zip_src }}" dest="{{ dir_grid_home }}" owner=oracle group=oinstall remote_src=yes creates="{{ dir_grid_home }}/gridSetup.sh"

- name: Installing cvuqdisk
  dnf: name="{{ dir_grid_home }}/cv/rpm/cvuqdisk-1.0.10-1.rpm" state=present disable_gpg_check=yes
  environment: { CVUQDISK_GRP: "oinstall" }

- name: Send grid instllation config
  template:
    src: grid_install.rsp.j2
    dest: "{{ grid_config_install }}"
    owner: oracle
    group: oinstall
    mode: '0600'

- name: Run grid setup
  become_user: oracle
  shell: |
    source ~/.bash_profile
    {{ dir_grid_home }}/gridSetup.sh -silent -responseFile {{ grid_config_install }} -waitforcompletion -ignorePrereqFailure
    RC=$?
    if [ $RC -eq 0 ] || [ $RC -eq 6 ]; then 
      touch {{ dir_grid_home }}/.ansible_grid_installed; 
      exit 0; 
    else 
      exit $RC; 
    fi
  environment: { CV_ASSUME_DISTID: "OEL7.6" }
  args:
    executable: /bin/bash
    creates: "{{ dir_grid_home }}/.ansible_grid_installed"

- name: Executing orainstRoot.sh
  command: "{{ dir_ora_inventory }}/orainstRoot.sh"
  args: { creates: "/etc/oraInst.loc" }

- name: Injecting environment variable to ssystemd
  command: systemctl set-environment CV_ASSUME_DISTID=OEL7.6
  changed_when: true

- name: Shutting down SELinux pernamently in config file
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=permissive

- name: Shutting down SELinux
  shell: setenforce 0
  failed_when: false

- name: Executing root.sh for Grid
  command: "{{ dir_grid_home }}/root.sh"
  environment: { CV_ASSUME_DISTID: "OEL7.6" }
  args: { creates: "/etc/oracle/olr.loc" }

- name: Running gridSetup.sh
  become_user: oracle
  command: "{{ dir_grid_home }}/gridSetup.sh -executeConfigTools -silent -responseFile {{ grid_config_install }}"
  environment: { CV_ASSUME_DISTID: "OEL7.6" }
  register: grid_config_tools
  failed_when: grid_config_tools.rc not in [0, 6]
  args:
    creates: "{{ dir_grid_home }}/network/admin/listener.ora"

- name: Adding RECOVERY disk group
  become_user: oracle
  command: "{{ dir_grid_home }}/bin/asmca -silent -createDiskGroup -diskGroupName RECOVERY -diskList {{ asm_rec_list }} -redundancy EXTERNAL"
  environment:
    ORACLE_HOME: "{{ dir_grid_home }}"
    ORACLE_SID: "+ASM"
  register: asmca_output
  failed_when: "asmca_output.rc != 0 and 'already exists' not in asmca_output.stdout"
