---
- name: Przesłanie pliku odpowiedzi dla DBCA (CDB+PDB)
  template:
    src: dbca_create.rsp.j2
    dest: "{{ path_dbc_create }}" 
    owner: oracle
    group: oinstall
    mode: '0600'

- name: Creating CDB+PDBs via Response File
  become_user: oracle
  shell: |
    source ~/.bash_profile
    {{ dir_db_home }}/bin/dbca -silent -createDatabase -responseFile {{ path_dbc_create }}
  args:
    creates: "{{ dir_oracle_base }}/admin/{{ name_cdb }}/adump"
    executable: /bin/bash

- name: Usunięcie pliku odpowiedzi z hasłami po udanej instalacji
  file:
    path: "{{ path_dbc_create }}"
    state: absent

- name: Configuring RMAN 
  become_user: oracle
  shell: |
    source ~/.bash_profile
    rman target / <<EOF
    CONFIGURE DEFAULT DEVICE TYPE TO DISK;
    CONFIGURE CONTROLFILE AUTOBACKUP ON;
    CONFIGURE BACKUP OPTIMIZATION ON;
    CONFIGURE CHANNEL DEVICE TYPE DISK FORMAT '{{ dir_mount_backup }}/{{ name_cdb }}/rman_backups/%d_%T_%U.bkp';
    CONFIGURE CONTROLFILE AUTOBACKUP FORMAT FOR DEVICE TYPE DISK TO '{{ dir_mount_backup }}/{{ name_cdb }}/autobackup/ctl_%F';
    CONFIGURE DEVICE TYPE DISK BACKUP TYPE TO COMPRESSED BACKUPSET;
    CONFIGURE ARCHIVELOG DELETION POLICY TO BACKED UP 1 TIMES TO DISK;
    CONFIGURE RETENTION POLICY TO RECOVERY WINDOW OF 5 DAYS;
    EXIT;
    EOF
  args:
    executable: /bin/bash

- name: Configuring logs paths in DB
  become_user: oracle
  shell: |
    source ~/.bash_profile
    sqlplus -s / as sysdba <<EOF
    ALTER SYSTEM SET audit_file_dest='{{ dir_db_logs }}/app/oracle/audit' SCOPE=SPFILE;
    ALTER SYSTEM SET diagnostic_dest='{{ dir_db_logs }}/app/oracle' SCOPE=SPFILE;
    SHUTDOWN IMMEDIATE;

    STARTUP MOUNT;
    ALTER DATABASE ARCHIVELOG;
    ALTER DATABASE OPEN;

    EXIT;
    EOF
  args:
    executable: /bin/bash
