---
- name: Unzip db binaries
  unarchive: src="{{ db_zip_src }}" dest="{{ dir_db_home }}" owner=oracle group=oinstall remote_src=yes creates="{{ dir_db_home }}/runInstaller"

- name: Send installation config
  template:
    src: db_install.rsp.j2
    dest: "{{ db_config_install }}"
    owner: oracle
    group: oinstall
    mode: '0600'

- name: Silent installing db engine 19.3.0
  become_user: oracle
  shell: |
    source ~/.bash_profile
    {{ dir_db_home }}/runInstaller -silent -responseFile {{ db_config_install }} -waitforcompletion -ignorePrereqFailure
    RC=$?
    if [ $RC -eq 0 ] || [ $RC -eq 6 ]; then 
      touch {{ dir_db_home }}/.ansible_db_installed; 
      exit 0; 
    else 
      exit $RC; 
    fi
  environment: { CV_ASSUME_DISTID: "OEL7.6" }
  args:
    executable: /bin/bash
    creates: "{{ dir_grid_home }}/.ansible_grid_installed"
