---
- name: Installing EPEL repo
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Installing dictinaries and apps
  dnf:
    name:
      - oracle-database-preinstall-19c
      - https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/getPackage/compat-libcap1-1.10-7.el7.x86_64.rpm
      - policycoreutils-python-utils
      - lvm2
      - kmod
      - libnsl
      - net-tools
      - psmisc
      - vim
      - tmux
      - unzip
      - rlwrap
      - s3fs-fuse
      - fuse
    state: present
    disable_gpg_check: yes

- name: Add groups ASM i DBA
  group: name="{{ item }}" state=present
  loop: [asmadmin, asmdba, asmoper, dba, oper, backupdba, dgdba, kmdba, racdba]

- name: Configuring oracle user
  user: name=oracle groups=asmadmin,asmdba,asmoper,dba,oper,backupdba,dgdba,kmdba,racdba append=yes

- name: Configuring environment
  block:
    - name: Create vim config
      copy:
        dest: "/home/{{ item }}/.vimrc"
        owner: "{{ item }}"
        group: oinstall
        content: |
          set number
          set relativenumber
      loop: [ec2-user, oracle]
    - name: Create tmux config
      copy:
        dest: "/home/{{ item }}/.tmux.conf"
        owner: "{{ item }}"
        group: oinstall
        content: |
          set -g mouse on
          set -g mode-keys vi
          bind h split-window -h -c "#{pane_current_path}"
          bind v split-window -v -c "#{pane_current_path}"
      loop: [ec2-user, oracle]
    - name: Update bashrc
      blockinfile:
        path: "/home/{{ item }}/.bashrc"
        owner: "{{ item }}"
        group: oinstall
        content: |
          set -o vi
      loop: [ ec2-user, oracle]
    - name: Update oracle user bashrc  
      blockinfile:
        path: "/home/oracle/.bashrc"
        owner: oracle
        group: oinstall
        marker: "# {mark} ANSIBLE MANAGED BLOCK - ORAENV"
        content: |
          export ORACLE_SID={{ name_cdb }}; 
          export ORAENV_ASK=NO 
          unset ORACLE_BASE ORACLE_HOME; 
          . /usr/local/bin/oraenv
          unset ORAENV_ASK
    - name: Update oracle user bash_profile
      blockinfile:
        path: "/home/oracle/.bash_profile"
        owner: oracle
        group: oinstall
        content: |
          if [ -f ~/.bashrc ]; then . ~/.bashrc; fi
          export GRID_HOME={{ dir_grid_home }}
          export DB_HOME={{ dir_db_home }}

          export ORACLE_BASE={{ dir_oracle_base }}
          export ORACLE_HOME=$DB_HOME
          export ORACLE_SID={{ name_cdb }} 
          export PATH=$GRID_HOME/bin:$ORACLE_HOME/bin:$PATH

          alias gridenv='export ORACLE_SID=+ASM; ORAENV_ASK=NO; unset ORACLE_BASE ORACLE_HOME; . /usr/local/bin/oraenv; unset ORAENV_ASK'
          alias dbenv='export ORACLE_SID={{ name_cdb }}; ORAENV_ASK=NO; unset ORACLE_BASE ORACLE_HOME; . /usr/local/bin/oraenv; unset ORAENV_ASK'
          alias ll='ls -lah'

- name: Searching 50GB disk
  shell: lsblk -dn -b -o NAME,SIZE | awk '$2 == 53687091200 {print $1}' | sort | head -n 1
  register: d_50g
  changed_when: false

- name: Searching 10GB disks 
  shell: lsblk -dn -b -o NAME,SIZE | awk '$2 == 10737418240 {print $1}' | sort
  register: d_10g
  changed_when: false

- name: Searching 5GB disks 
  shell: lsblk -dn -b -o NAME,SIZE | awk '$2 == 5368709120 {print $1}' | sort
  register: d_5g
  changed_when: false

- name: Setting lists with disks
  set_fact:
    lvm_volumes:
      - { device: "/dev/{{ d_50g.stdout }}", vg: "u01vg", lv: "binlv", mount: "/u01" }
      - { device: "/dev/{{ d_10g.stdout_lines[0] }}", vg: "u02vg", lv: "loglv", mount: "{{ dir_db_logs }}" }
    asm_all_raw: "{{ d_10g.stdout_lines[1:] + d_5g.stdout_lines }}"
    asm_data_list: "{{ d_10g.stdout_lines[1:] | map('regex_replace', '^(.*)$', '/dev/\\1') | join(',') }}"
    asm_rec_list: "{{ d_5g.stdout_lines | map('regex_replace', '^(.*)$', '/dev/\\1') | join(',') }}"


- name: Create and mount LVMs
  block:
    - file: path="{{ item.mount }}" state=directory mode='0755'
      loop: "{{ lvm_volumes }}"
    - lvg: vg="{{ item.vg }}" pvs="{{ item.device }}"
      loop: "{{ lvm_volumes }}"
    - lvol: vg="{{ item.vg }}" lv="{{ item.lv }}" size=100%FREE
      loop: "{{ lvm_volumes }}"
    - filesystem: fstype=xfs dev="/dev/{{ item.vg }}/{{ item.lv }}"
      loop: "{{ lvm_volumes }}"
    - mount: path="{{ item.mount }}" src="/dev/{{ item.vg }}/{{ item.lv }}" fstype=xfs opts=defaults state=mounted
      loop: "{{ lvm_volumes }}"
    - file: path="{{ item.mount }}" owner=oracle group=oinstall state=directory recurse=yes
      loop: "{{ lvm_volumes }}"

- name: Create and reload udev rules
  copy:
    dest: /etc/udev/rules.d/99-oracle-asmdevices.rules
    content: |
      {% for disk in asm_all_raw %}
      KERNEL=="{{ disk }}", OWNER="oracle", GROUP="asmadmin", MODE="0660"
      {% endfor %}
    mode: '0644'
- shell: udevadm control --reload-rules && udevadm trigger
  changed_when: true


- name: Getting sys IDs
  command: id -{{ item }} oracle
  register: ids
  loop: ['u', 'g']
  changed_when: false

- name: Mounting S3 buckets
  block:
    - modprobe: name=fuse state=present
    - file: path="{{ item }}" state=directory owner=oracle group=oinstall mode='0775'
      loop: ["{{ dir_mount_golden }}", "{{ dir_mount_backup }}"]
    - file: src=/usr/bin/s3fs dest=/sbin/mount.s3fs state=link
    - mount: path="{{ dir_mount_golden }}" src="{{ s3_golden }}" fstype=s3fs opts="_netdev,allow_other,iam_role=auto,url=https://s3.eu-central-1.amazonaws.com,endpoint=eu-central-1,uid={{ ids.results[0].stdout }},gid={{ ids.results[1].stdout }},umask=022,connect_timeout=5,retries=3" state=mounted
    - mount: path="{{ dir_mount_backup }}" src="{{ s3_backup }}" fstype=s3fs opts="_netdev,allow_other,iam_role=auto,url=https://s3.eu-central-1.amazonaws.com,endpoint=eu-central-1,uid={{ ids.results[0].stdout }},gid={{ ids.results[1].stdout }},umask=022,connect_timeout=5,retries=3" state=mounted


- name: Creating Grid and Invetory directoires
  file: 
    path: "{{ item }}" 
    state: directory
    owner: oracle
    group: oinstall 
    mode: '0775' 
    recurse: yes
  loop: 
    - "{{ dir_grid_home }}"
    - "{{ dir_db_home }}"
    - "{{ dir_ora_inventory }}"
    - "{{ dir_db_logs }}/oradata"
    - "{{ dir_db_logs }}/backup_logs"
    - "{{ dir_db_logs }}/app/oracle"
    - "{{ dir_db_logs }}/app/oracle/diag"
    - "{{ dir_db_logs }}/app/oracle/audit"
    - "{{ dir_mount_backup }}/{{ name_cdb }}/rman_backups"

